### DISCUSSION TITLE
Delay upgrade of cluster nodes

### DISCUSSION THREAD

**Discussion by seimic** [rancher/system-upgrade-controller#177] [Q&A]
Hi,

is there a way to delay the upgrade of nodes in a cluster?
I mean to upgrade one by one but with a delay of lets say 5 minutes to make sure all pods
on the upgraded server are in ready state.
There are some deployments (cilium and mongodb for example) which need more time to 
come up and if the upgrade goes too fast all mongodb cluster nodes are in unready state.

Example: Upgrade of 3 nodes RKE2 cluster (3 master nodes only).

```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-server-1.21.8-plan
  namespace: system-upgrade
  labels:
    rke2-upgrade: server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
       - {key: rke2-upgrade, operator: Exists}
       - {key: rke2-upgrade, operator: NotIn, values: ["disabled", "false"]}
       - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/rke2-upgrade
  version: v1.21.8+rke2r1
``` 

The upgrade finishes faster than the initialization of the mongodb nodes in this cluster.
This results in an unnecessary downtime of the deployment.

Kind regards,
Michael
