### DISCUSSION TITLE
MicroOS: if node is not restarted because there is nothing to do, then the node will remain unsheduleable.

### DISCUSSION THREAD

**Discussion by jhoelzel** [rancher/system-upgrade-controller#261] [Q&A]
Hey Guys, im using the upgrader and if i force a reboot everything works fine.

I am working on the MicroOS based example that can be found in this repository and here is my plan and my script:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: microos
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)
    transactional-update --continue cleanup dup
    # For a delayed reboot use:
    #   rebootmgrctl reboot
    # or chain it with transactional-update commands:
    #   transactional-update --continue cleanup dup reboot
    [ -f /run/reboot-needed ] && rebootmgrctl reboot now
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: microos-master
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
    - key: rke2-upgrade
      operator: NotIn
      values:
      - disabled
      - "false"
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  secrets:
    - name: microos
      path: /host/run/system-upgrade/secrets/microos
  cordon: true
  version: microos
  upgrade:
    image: registry.opensuse.org/opensuse/tumbleweed:latest
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/microos/upgrade.sh"]
```

otherwise im using the vanilla manifest provided in the repository here: 
https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml

note that the original script contains    `  [ -f /run/reboot-needed ] && rebootmgrctl reboot now` which means it should only reboot if something changes.

Well i run dup on provisioning and therefore the node is up to date and nothing happens but a bit of cleanup. BUT my node hangs.
The job fails because it seems to be expecting a reboot and the only way to fix it was to remove`  [ -f /run/reboot-needed ] ` from the script in order to have it reboot the instance (then the taint disappears and the jobs succeeds).

Now to my actual questions:

Is this desired behavior?
Should i really hard reboot the node even if its not needed?
What can i do to prevent this?
