### DISCUSSION TITLE
Kernel version is not getting upgraded

### DISCUSSION THREAD

**Discussion by MANUDEV-H-MENON** [rancher/system-upgrade-controller#322] [Q&A]
I am planning to upgrade kernel versions of node using system-upgrade-controller.
Steps taken for kernel upgrade 
1.Run below files to install system upgrade controller
`kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
`
(Ensure crds are installed first if not run  kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml )
Configure node  with label kernel-upgrade=true

3.Configure a plan and secret for kernel upgrade

```
apiVersion: v1
kind: Secret
metadata:
  name: kernel
  namespace: system-upgrade
type: Opaque
stringData:
  version: 6.1.0-23
  upgrade.sh: |
    #!/bin/sh
    set -e
    export DEBIAN_FRONTEND=noninteractive
    secrets=$(dirname $0)
    apt-get update
    apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -yq \
      linux-image-$(cat $secrets/version)-amd64 \
      linux-headers-$(cat $secrets/version)-amd64
    if [ -f /run/reboot-required ]; then
      cat /run/reboot-required
      reboot
    fi
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kernel
  namespace: system-upgrade
spec:
  concurrency: 2
  nodeSelector:
    matchExpressions:
      - key: kernel-upgrade
        operator: In
        values: ["true"]
      - {key: kernel-upgrade, operator: Exists}
  serviceAccountName: system-upgrade
  secrets:
    - name: kernel
      path: /host/run/system-upgrade/secrets/kernel
  version: bookworm
  drain:
    force: true
  upgrade:
    image: debian:bookworm
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/kernel/upgrade.sh"]
```

This shall execute the jobs and upgrade the kernel.
But it is not rebooting because if condition is not getting true.
New kernel packages are installed, but it is not reflected unless and until reboot occurs.

**May i know why this happens ? initially on package update if condition should work.**
Only manual reboot is helping to change the version.
I had explicitly gave reboot command outside if condition in **upgrade.sh** script.
Then Host master node where job is executing , is getting log out and does infinite time start and restart.
 **any suggestion that will this reboot and kernel upgrade works without disconnecting from host ?**
I have taken reference from here : https://github.com/rancher/system-upgrade-controller/blob/master/examples/ubuntu/bionic/linux-kernel-virtual-hwe-18.04.yaml
