### ISSUE TITLE
error getting latest release because "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by sseneca** [rancher/system-upgrade-controller#105]
**Version**
`system-upgrade-controller version v0.6.2 (9ed50a5)`

**Platform/Architecture**
linux-amd64

**Describe the bug**
After applying a `Plan`, omitting the `version` field and setting the `channel` field to a URL that resolves to a release of k3 as described in [the documentation](https://rancher.com/docs/k3s/latest/en/upgrades/automated/#configure-plans), the controller will complain:

```
W1010 07:58:53.832507       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-10-10T07:58:53Z" level=info msg="Creating CRD plans.upgrade.cattle.io"
time="2020-10-10T07:58:54Z" level=info msg="Waiting for CRD plans.upgrade.cattle.io to become available"
time="2020-10-10T07:58:54Z" level=info msg="Done waiting for CRD plans.upgrade.cattle.io to become available"
time="2020-10-10T07:58:54Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2020-10-10T07:58:54Z" level=info msg="Starting upgrade.cattle.io/v1, Kind=Plan controller"
time="2020-10-10T07:58:54Z" level=info msg="Starting /v1, Kind=Node controller"
time="2020-10-10T07:58:54Z" level=info msg="Starting batch/v1, Kind=Job controller"
E1010 08:07:35.109182       1 controller.go:135] error syncing 'system-upgrade/server-plan': handler system-upgrade-controller: Get https://update.k3s.io/v1-release/channels/latest: x509: certificate signed by unknown authority, requeuing
```

This repeats continuously.

**To Reproduce**

Install the system upgrade controller:

```
kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.6.2/system-upgrade-controller.yaml
```

Apply the following plan:

```yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/latest
```

**Expected behavior**
It should find the latest release.

**Actual behavior**
It doesn't find the latest release due to "certificate signed by unknown authority".

**Additional context**
I saw a similar issue in #94. The system *does* have `/etc/ssl/`, and the system is up to date.

**Comment by jenting** [comment]
@sseneca,
Please check the host system has the symbolic link files/folders under `/etc/ssl/`.
If yes, please also mount the symbolic link files/folders from the host to the container pods.

For example, under host OS, the `/etc/ssl/` have two symbolic link:
```shell
lrwxrwxrwx 1 root root    38 Sep 30  2018 ca-bundle.pem -> /var/lib/ca-certificates/ca-bundle.pem
lrwxrwxrwx 1 root root    28 Sep 30  2018 certs -> /var/lib/ca-certificates/pem
-rw-r--r-- 1 root root   412 Jun  6 00:54 ct_log_list.cnf
-rw-r--r-- 1 root root   412 Jun  6 00:54 ct_log_list.cnf.dist
-rw-r--r-- 1 root root 10909 Jun  6 00:54 openssl.cnf
drwx------ 1 root root     0 Jun  6 00:54 private
```

so I mount the `/var/lib/ca-certificates` from host to the container pods by adding
```yaml
...
        volumeMounts:
        - mountPath: /etc/ssl
          name: etc-ssl
        - mountPath: /var/lib/ca-certificates
          name: var-lib
      volumes:
      - hostPath:
          path: /etc/ssl
          type: Directory
        name: etc-ssl
      - hostPath:
          path: /var/lib/ca-certificates
          type: Directory
        name: var-lib
...
```

**Comment by sseneca** [comment]
Yep, `/etc/ssl/cert.pem -> /etc/ca-certificates/extracted/tls-ca-bundle.pem` existed so I mounted `/etc/ca-certificates/extracted` and am no longer having this issue.

**Comment by AaronJaegerVA** [comment]
> @sseneca,
> Please check the host system has the symbolic link files/folders under `/etc/ssl/`.
> If yes, please also mount the symbolic link files/folders from the host to the container pods.
> 
> For example, under host OS, the `/etc/ssl/` have two symbolic link:
> 
> ```shell
> lrwxrwxrwx 1 root root    38 Sep 30  2018 ca-bundle.pem -> /var/lib/ca-certificates/ca-bundle.pem
> lrwxrwxrwx 1 root root    28 Sep 30  2018 certs -> /var/lib/ca-certificates/pem
> -rw-r--r-- 1 root root   412 Jun  6 00:54 ct_log_list.cnf
> -rw-r--r-- 1 root root   412 Jun  6 00:54 ct_log_list.cnf.dist
> -rw-r--r-- 1 root root 10909 Jun  6 00:54 openssl.cnf
> drwx------ 1 root root     0 Jun  6 00:54 private
> ```
> 
> so I mount the `/var/lib/ca-certificates` from host to the container pods by adding
> 
> ```yaml
> ...
>         volumeMounts:
>         - mountPath: /etc/ssl
>           name: etc-ssl
>         - mountPath: /var/lib/ca-certificates
>           name: var-lib
>       volumes:
>       - hostPath:
>           path: /etc/ssl
>           type: Directory
>         name: etc-ssl
>       - hostPath:
>           path: /var/lib/ca-certificates
>           type: Directory
>         name: var-lib
> ...
> ```

How are you adding these mounts? A hot edit like `kubectl edit pod/system-upgrade-controller-b64b5bcb7-bpmkr -n system-upgrade` or something more clever?

**Comment by sseneca** [comment]
If you use GitOps, something like what I did in the above referenced commit works: https://github.com/sseneca/k8s-server/commit/dd1acc66d3998537ffa68f43db52662e973b657f

A hot edit would also work, though you should edit the deployment not the pod, i.e. `kubectl edit deployment/system-upgrade-controller -n system-upgrade`

If you're installing for the first time, just edit the YAML before you `kubectl apply -f`

**Comment by AaronJaegerVA** [comment]
I tried editing the deployment. I am running on top of RHEL so I had to use `/etc/pki/../..` instead of `/etc/ssl/certs`. Maybe I chose the wrong directly, but it did not work and I still get `unknown authority` errors.

**Comment by sseneca** [comment]
>  `/etc/pki/../..`

This is probably incorrect, it points to the root directory. You'll want to use an absolute path to wherever is symlinked to in `/etc/ssl`. My guess is mounting `/etc/pki` will work, but I'm not familiar with RHEL

**Comment by AaronJaegerVA** [comment]
I may have been unclear. I could not remember the entire path so I used an abbreviation.

The actual path is /etc/pki/tls/certs​


Sincerely,


Aaron Jaeger (contractor)

ETS Testing Systems Engineering & Implementation

Sr. Systems Engineer

Planned Systems International (PSI), Inc.

Enterprise Testing Service (Station 116) (005Q)

VA OIT EPMD

Office: 727-320-1972

Cell: 727-386-9505


For general information on ETS, refer to https://dvagov.sharepoint.com/sites/OITEPMOETS<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FOITEPMOETS&data=04%7C01%7C%7Cf3426df4e7b249bae41408d8d8499ecd%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637497158011287842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZKd5W7b9p50OHjVXeYyTaxZtg1urUYqfORDVmwbT%2BD0%3D&reserved=0> or email us at VA OIT ETS ENGAGE or ETSENGAGE@va.gov<mailto:ETSENGAGE@va.gov>.

________________________________

**Comment by sseneca** [comment]
If you mounted all the symlinked paths and you're still getting the error then it's probably a different bug worth its own issue

**Comment by AaronJaegerVA** [comment]
I am still having some trouble. If my host has this:

```
[root@vhaispvchdck001 rke2-upgrade]# ls -l /etc/ssl
total 4
lrwxrwxrwx. 1 root root   16 Jul 10  2020 certs -> ../pki/tls/certs
drwx------. 2 root root 4096 Jun  5  2020 vhaispvchdck001.vha.med.va.gov
```

```
[root@vhaispvchdck001 rke2-upgrade]# cd /etc/ssl/certs
[root@vhaispvchdck001 certs]# ls -l
total 12
lrwxrwxrwx. 1 root root   49 Jul 10  2020 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx. 1 root root   55 Jul 10  2020 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
-rwxr-xr-x. 1 root root  610 Dec  4 11:47 make-dummy-cert
-rw-r--r--. 1 root root 2516 Dec  4 11:47 Makefile
-rwxr-xr-x. 1 root root  829 Dec  4 11:47 renew-dummy-cert
```

Am I supposed to mount both `/etc/pki/ca-trust/extracted/pem` and `/etc/pki/ca-trust/extracted/openssl`?

If so, where should these be mounted in the container? It seems like the container is apline-based, so mounting my RHEL hosts directories into the alpine container on the same paths wouldn't help the alpine find the certs.

**Comment by sseneca** [comment]
My guess is that as long as the container can access the location the links are pointing to it should work. So instead of mounting `/etc/pki/ca-trust/ ... `, mount `/etc/pki` to the same path within the container. The container will then be able to follow all the links to the correct directory.

So something like this:

```yaml
        volumeMounts:
        ...
        - mountPath: /etc/pki
          name: etc-pki
      volumes:
      ...
      - hostPath:
          path: /etc/pki
          type: Directory
        name: etc-pki
```
