### ISSUE TITLE
by default only deploy on master nodes

### ISSUE THREAD

**Issue by dweomer** [rancher/system-upgrade-controller#13]
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {key: "node-role.kubernetes.io/master", operator: In, values: ["true"]}
```
