### ISSUE TITLE
Controller cannot be scheduled on kuberadm-created clusters

### ISSUE THREAD

**Issue by mhutter** [rancher/system-upgrade-controller#136]
**Version**
v0.7.5

**Platform/Architecture**
* Kubernetes 1.21 via kubeadm on Ubuntu 20.04
* SUC v0.7.5 installed via Kustomize, no adjustments otherwise

**Describe the bug**
The SUC has an affinity rule scheduling the controller onto nodes that are labelled with `node-role.kubernetes.io/master: "true"`.
However, for some versions now the "node-role" labels are applied without a value:

```yaml
apiVersion: v1
kind: Node
metadata:
  name: master-0
  labels:
    node-role.kubernetes.io/master: ""
...
```

Hence the controller cannot be scheduled and stays in "pending"

**To Reproduce**
* Install cluster with kubeadm, deploy SUC

**Expected behavior**
Controller is started on a master system

**Actual behavior**
Controller cannot be scheduled

**Additional context**
FWIW, the cluster runs on Hetzner Cloud and is using the hcloud-cloud-controller-manager.

Should I send a PR to fix the issue?
