### ISSUE TITLE
Plans never get executed

### ISSUE THREAD

**Issue by clambin** [rancher/system-upgrade-controller#147]
**Version**
rancher/system-upgrade-controller:v0.7.5

**Platform/Architecture**
linux/arm64

**Describe the bug**
For some reason, my plans are no longer getting executed.  Here's my two plans:

```
# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
  labels:
    k3s-update: server
spec:
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/stable
  nodeSelector:
    matchExpressions:
    - {key: node-role.kubernetes.io/master, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/stable
  nodeSelector:
    matchExpressions:
    - {key: node-role.kubernetes.io/master, operator: DoesNotExist}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "server-plan"]
  drain:
    force: true
    skipWaitForDeleteTimeout: 60
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
```

I'm running a k3s cluster with one master and three worker nodes:

```
NAME      STATUS   ROLES                  AGE    VERSION
master1   Ready    control-plane,master   131d   v1.21.4+k3s1
worker3   Ready    <none>                 131d   v1.21.3+k3s1
worker2   Ready    <none>                 131d   v1.21.3+k3s1
worker1   Ready    <none>                 131d   v1.21.3+k3s1
```

I upgraded the master node manually (I've been struggling with this problem for a while).  But the controller never triggers the updates.  I activated debug logging on the controller:

```
W0916 19:41:04.986567       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-09-16T19:41:05Z" level=info msg="Applying CRD plans.upgrade.cattle.io" func="github.com/rancher/wrangler/pkg/crd.(*Factory).createCRD" file="/go/pkg/mod/github.com/rancher/wrangler@v0.8.1-0.20210424045532-c389a3e0ae51/pkg/crd/init.go:503"
time="2021-09-16T19:41:07Z" level=debug msg="DesiredSet - No change(2) apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /plans.upgrade.cattle.io for  plans.upgrade.cattle.io" func="github.com/rancher/wrangler/pkg/apply.(*desiredSet).compareObjects" file="/go/pkg/mod/github.com/rancher/wrangler@v0.8.1-0.20210424045532-c389a3e0ae51/pkg/apply/desiredset_compare.go:248"
time="2021-09-16T19:41:07Z" level=info msg="Starting /v1, Kind=Node controller" func="github.com/rancher/lasso/pkg/controller.(*controller).run" file="/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:125"
time="2021-09-16T19:41:07Z" level=info msg="Starting /v1, Kind=Secret controller" func="github.com/rancher/lasso/pkg/controller.(*controller).run" file="/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:125"
time="2021-09-16T19:41:07Z" level=info msg="Starting batch/v1, Kind=Job controller" func="github.com/rancher/lasso/pkg/controller.(*controller).run" file="/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:125"
time="2021-09-16T19:41:07Z" level=info msg="Starting upgrade.cattle.io/v1, Kind=Plan controller" func="github.com/rancher/lasso/pkg/controller.(*controller).run" file="/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:125"
time="2021-09-16T19:41:07Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func1" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:30"
time="2021-09-16T19:41:07Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func2" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:68"
time="2021-09-16T19:41:07Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade/server-plan@24669471, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func1" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:30"
time="2021-09-16T19:41:07Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade/server-plan@24669471, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func2" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:68"
time="2021-09-16T19:43:44Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func1" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:30"
time="2021-09-16T19:43:44Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func2" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:68"
time="2021-09-16T19:43:54Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func1" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:30"
time="2021-09-16T19:43:54Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func2" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:68"
time="2021-09-16T19:43:54Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func1" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:30"
time="2021-09-16T19:43:54Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade/agent-plan@24669470, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2021-09-16T19:39:09Z LastTransitionTime: Reason:Channel Message:}] LatestVersion:v1.21.4-k3s1 LatestHash:57eb7803114642f8ff2061b7aee4d0bf7606d79e1eb8454da54e1f41 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func2" file="/go/src/github.com/rancher/system-upgrade-controller/pkg/upgrade/handle_upgrade.go:68"
``` 

These entries keep repeating, without any errors. Clearly, it's seeing there's a more recent version, but the updates never start.

**To Reproduce**
1. Install controller and apply plans as per above
2. Nodes should be upgraded

**Expected behavior**
Nodes should be upgraded, or an error should be shown.

**Actual behavior**
No upgrades occur.

**Additional context**
Already was seeing this problem with the master nodes (haven't found the root cause, but checked the obvious like the nodeSelector criteria), but now agents are no longer getting upgraded.
