### ISSUE TITLE
Agent stuck in podinitializing

### ISSUE THREAD

**Issue by fabricesemti80** [rancher/system-upgrade-controller#165]
**Version**

Can't connect to the controller, the message is:

```sh
➜ kubectl exec -i -t -n system-upgrade system-upgrade-controller-7bc9cd65fb-4q2bl -c system-upgrade-controller "--" sh -c "clear; (bash || ash || sh)"
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "a9d83cd251fd609518a712d05261cc8ad0be97cf1432df48b1a1c34f806b5332": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown
```

But it should be v0.8.0 according to the Kustomization

**Platform/Architecture**

Ubuntu 20004 and k3s v1.21.5

**Describe the bug**

Agent node is always stays in "pod initialising" state, then after 15 min terminates.

pod details:

```sh
11:07:46 fabrice@DESKTOP-FS k8s-home-cluster-mk3 ±|main|→ k describe pod apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-pjcrk
+ kubectl describe pod apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-pjcrk
Name:         apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-pjcrk
Namespace:    system-upgrade
Priority:     0
Node:         k8s-2/192.168.1.21
Start Time:   Wed, 10 Nov 2021 11:15:58 +0000
Labels:       controller-uid=5c365998-3cb5-4cea-a93e-71e5017b4c39
              job-name=apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-22a35
              plan.upgrade.cattle.io/k3s-agent=dad65bb3d0bee147c31555035d3398b17faecb5ff69c1db15f04d90b
              upgrade.cattle.io/controller=system-upgrade-controller
              upgrade.cattle.io/node=k8s-2
              upgrade.cattle.io/plan=k3s-agent
              upgrade.cattle.io/version=v1.21.6-k3s1
Annotations:  <none>
Status:       Pending
IP:           192.168.1.21
IPs:
  IP:           192.168.1.21
Controlled By:  Job/apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-22a35
Init Containers:
  prepare:
    Container ID:  containerd://7ffa954b80498246d79d127469fd630c4869a264ab156bacd99acb1ddbfa9a12
    Image:         rancher/k3s-upgrade:v1.21.6-k3s1
    Image ID:      docker.io/rancher/k3s-upgrade@sha256:b79c123ed99e4b9e63269cb978d59fee71e5378046a3e693436aa4c2711c9a12
    Port:          <none>
    Host Port:     <none>
    Args:
      prepare
      k3s-server
    State:          Running
      Started:      Wed, 10 Nov 2021 11:16:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:             apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-pjcrk (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            k3s-agent
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     dad65bb3d0bee147c31555035d3398b17faecb5ff69c1db15f04d90b
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  v1.21.6-k3s1
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-b8wz4 (ro)
Containers:
  upgrade:
    Container ID:   
    Image:          rancher/k3s-upgrade:v1.21.6-k3s1
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:             apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-pjcrk (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            k3s-agent
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     dad65bb3d0bee147c31555035d3398b17faecb5ff69c1db15f04d90b
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  v1.21.6-k3s1
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-b8wz4 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  host-root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  Directory
  pod-info:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  kube-api-access-b8wz4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  73s   default-scheduler  Successfully assigned system-upgrade/apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-pjcrk to k8s-2
  Normal  Pulling    73s   kubelet            Pulling image "rancher/k3s-upgrade:v1.21.6-k3s1"
  Normal  Pulled     72s   kubelet            Successfully pulled image "rancher/k3s-upgrade:v1.21.6-k3s1" in 930.861628ms
  Normal  Created    72s   kubelet            Created container prepare
  Normal  Started    72s   kubelet            Started container prepare
11:17:12 fabrice@DESKTOP-FS k8s-home-cluster-mk3 ±|main|→ 

```

**To Reproduce**

here are my configs:

kustomization.yaml

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/system-upgrade-controller?ref=v0.8.0
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.8.0
```

server-plan.yaml

```yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.21
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
          - "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
  upgrade:
    image: rancher/k3s-upgrade
```
agent-plan.yaml

```yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.21
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: NotIn
        values:
          - "true"
  prepare:
    image: rancher/k3s-upgrade
    args:
      - "prepare"
      - "k3s-server"
  upgrade:
    image: rancher/k3s-upgrade
```

(I omitted the other kustomization-files as these are only point to these)

**Expected behavior**

agent-server pods reach "running" state...?

**Actual behavior**

As described above. Also logs from the controller:

```sh
W1110 10:43:45.567701       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-11-10T10:43:46Z" level=info msg="Applying CRD plans.upgrade.cattle.io"
time="2021-11-10T10:43:47Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-11-10T10:43:47Z" level=info msg="Starting /v1, Kind=Node controller"
time="2021-11-10T10:43:47Z" level=info msg="Starting batch/v1, Kind=Job controller"
time="2021-11-10T10:43:47Z" level=info msg="Starting upgrade.cattle.io/v1, Kind=Plan controller"
time="2021-11-10T11:15:58Z" level=error msg="error syncing 'system-upgrade/apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-22a35': handler system-upgrade-controller: jobs.batch \"apply-k3s-agent-on-k8s-2-with-dad65bb3d0bee147c31555035d3-22a35\" not found, requeuing"
```

**Additional context**

My source for the cluster build:

https://github.com/k8s-at-home/template-cluster-k3s

My current code:

https://github.com/fabricesemti80/k8s-home-cluster-mk3
