### ISSUE TITLE
CRD for Plan Not Available For Deployment

### ISSUE THREAD

**Issue by texasbobs** [rancher/system-upgrade-controller#172]
We are running version rancher/system-upgrade-controller:v0.6.2 of the system upgrade controller.  The `deployment` creates the CRD for `plan` at startup.  This means that while the files are being applied to the cluster, the creation of any plans fails.  This causes issues with tools like Flux which presents all of the YAMLs to kubernetes for validation.  Kubernetes reports the error and the deployment fails.

We would like the YAML for the CRD to be available instead of it being created at startup.

**Comment by billykwooten** [comment]
I've seen this as well, when using gitops processes since this is dynamically created and not a static file, it's sort of an anti-pattern against Kubernetes and descriptive files.

You can see issues related to this topic in https://github.com/fluxcd/flux2/discussions/1916 for example

**Comment by texasbobs** [comment]
Any thoughts on making the CRD part of the included yaml file? We're not able to use GitOps with this configuration.

**Comment by brandond** [comment]
The PR I just linked would make the CRD manifest available as a GitHub release artifact. This is preferred over having it checked in to the repo, as it is actually generated dynamically by the controller at startup.

**Comment by texasbobs** [comment]
That looks like it would work.  Thanks for the PR.  What do you think about the likelihood of it getting approved?

**Comment by texasbobs** [comment]
> The PR I just linked would make the CRD manifest available as a GitHub release artifact. This is preferred over having it checked in to the repo, as it is actually generated dynamically by the controller at startup and does not exist in YAML format anywhere in the codebase.

So the CRD is not going to exist in the manifest?  I'm not seeing any update there.

**Comment by onedr0p** [comment]
It would be nice if system-upgrade-controller had this folder structure to support the deploying the manifests and crds with kustomize:

```
deploy/
    crds/
        kustomization.yaml
        crds.yaml
    manifests/
        kustomization.yaml
        system-upgrade-controller.yaml
```

**Comment by onedr0p** [comment]
Sorry for triple posting, but for the people using Flux it would be nice to do the following since using an `http/s` resource in a `kustomization` is not recommended to do.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: system-upgrade-controller-manifests
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/rancher/system-upgrade-controller
  ref:
    tag: v0.10.0
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/deploy/crds
    !/deploy/mainifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-system-upgrade-controller-crds
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller-manifests
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-system-upgrade-controller-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-system-upgrade-controller-crds
  interval: 10m
  path: ./deploy/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller-manifests
  wait: true
```

Hopefully we can see this change come. Thanks
