### ISSUE TITLE
Usage with package manager based Operating Systems

### ISSUE THREAD

**Issue by tobru** [rancher/system-upgrade-controller#19]
**Is your feature request related to a problem? Please describe.**

I want to use SUC with classic package manager based operating systems like Ubuntu, RHEL or Alpine which IMHO and according to the README ("Purporting to support general-purpose node upgrades...") should be supported by SUC.

In this issue I want to figure out this use-case in detail and what's needed for SUC to fully support it (hint: It doesn't currently).

**Describe the solution you'd like**

In my experiments with Ubuntu I crafted the following plan:

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: ubuntu-latest
  namespace: system-upgrade
spec:
  concurrency: 1
  version: latest
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/ubuntu-latest, operator: Exists}
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: busybox
    command:
      - chroot
      - /host
    args:
      - sh
      - -c
      - |
        export DEBIAN_FRONTEND=noninteractive && \
        apt-get -q update && \
        apt-get -qy dist-upgrade --auto-remove --purge && \
        [ -f /var/run/reboot-required ] && cat /var/run/reboot-required && reboot
```

To make this plan work, the following tweak is needed to get working network connectivity in the upgrade Pod:

```
--- a/pkg/upgrade/job/job.go
+++ b/pkg/upgrade/job/job.go
@@ -99,6 +99,7 @@ func NewUpgradeJob(plan *upgradeapiv1.Plan, nodeName, controllerName string) *ba
                                Spec: corev1.PodSpec{
                                        HostIPC:            true,
                                        HostPID:            true,
+                                       HostNetwork:        true,
                                        ServiceAccountName: plan.Spec.ServiceAccountName,
                                        Affinity: &corev1.Affinity{
                                                NodeAffinity: &corev1.NodeAffinity{
```

With that, the Plan does it's job, creates Jobs and runs Pods which will actually run upgrades on the nodes. So far so good. Now to the questions:

* As installing updates via package manager there is no such thing like "channels", at least not without using something like Satellite or a similar tool. But even then, the `channel` or `version` doesn't map to a container image tag. Are there already ideas to solve this?
* How could the controller be ableto figure out to undrain a node after upgrades with reboots? It seems not to work with reboots because after a reboot the Pod get's rescheduled but the node is still drained.
* What do you think about this mechanism of upgrading OS packages?

**Describe alternatives you've considered**

SUC is THE BEST, there are no real alternatives :smile:
