### ISSUE TITLE
Spawned jobs use broken (truncated) image names

### ISSUE THREAD

**Issue by webD97** [rancher/system-upgrade-controller#206]
**Version**
system-upgrade-controller version v0.9.1 (79da9f0)

**Platform/Architecture**
linux-amd64

**Describe the bug**
The jobs spawned by SUC use an image name truncated at 64 characters. This leads to Kubernetes not being able to run the jobs since these images simply do not exist. 

**To Reproduce**
We experienced the bug with the following `Plan`. Please note that I cannot post company internal image and plan names so I had to replace them. Either way, the images are not publicly available. Please also note that we have configured a registry mirror to avoid having to specify an explicit registry. The key point for reproduction is that the image name must be longer than 64 characters. In our case, the image names are that long because we are using a deeply nested structure in GitLab to organize our code base.

```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: xxxxxx
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
          - "true"
  upgrade:
    image: aa/bbbb/ccccccccccccccccc/dddddddddddddddddd/eeeeeeeeee/xxxxxx/master
    command: ["/usr/local/bin/bash"]
    args: ["/root/install.sh"]
  concurrency: 1
  version: "981a1f90cfcad63ea864957f996cde9b2e99e587"
```

SUC will pick up this plan and spawn a job to execute it. Kubernetes will then spawn pods accordingly which will fail due to the "truncated" image not existing. I was not able to describe the job or its pods because SUC seems to constantly replace the job. Using the configmap, I was able to enable debug mode though (`SYSTEM_UPGRADE_CONTROLLER_DEBUG: true`) and it seems to then log the job spec as JSON. This reveals the truncated image name in `spec.template.spec.containers[0].image`: `aa/bbbb/ccccccccccccccccc/dddddddddddddddddd/eeeeeeeeee/xxxxxx/m`

**Expected behavior**
I expect the spawned jobs to use the correct image name. In this example, this would be `aa/bbbb/ccccccccccccccccc/dddddddddddddddddd/eeeeeeeeee/xxxxxx/master:981a1f90cfcad63ea864957f996cde9b2e99e587`.

**Actual behavior**
The jobs use an image named truncated at 64 characters: `aa/bbbb/ccccccccccccccccc/dddddddddddddddddd/eeeeeeeeee/xxxxxx/m`.

**Additional context**
None - but I'm happy to provide more information if required.

**Comment by webD97** [comment]
Hm, after some deeper research the name does seem to stay truncated. At some point, I now managed to get one job as yaml via kubectl and this yaml seems to have the correct image name

**Comment by webD97** [comment]
Regardless of this, SUC keeps deleting and creating the same job over and over without giving it time to run. The same job name has a different `.metadata.uid` every few seconds

**Comment by ntx-ben** [comment]
This looks like this issue which I reported a while back:

#164

**Comment by webD97** [comment]
It's not my image's fault, I have the same problem even if it's some bash:latest image which only prints "hello world"

**Comment by dweomer** [comment]
Shoot, this smells like a wrangler bug.

**Comment by brandond** [comment]
I am unable to replicate this with `rancher/system-upgrade-controller:v0.10.0-dev.2`:

I mirrored the library/busybox image to a local registry with a very long name, and the resulting Job spec is correct:

```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: busybox-test
  namespace: system-upgrade
spec:
  nodeSelector:
    matchExpressions:
    - key: kubernetes.io/os
      operator: In
      values:
      - linux
  upgrade:
    image: local.registry.k3s.khaus/e6b2900c03ccaf3a32b6020cadfdfc46eac4889ddf603ea39d66082504a5e7c3/busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 60"]
  concurrency: 1
  version: "1.35.0-uclibc"
```

```console
brandond@dev01:~/suc-test$ kubectl describe job -n system-upgrade -l upgrade.cattle.io/plan=busybox-test
Name:                     apply-busybox-test-on-k3s-server-1-with-7dfd8044aa7c45620-3655e
Namespace:                system-upgrade
Selector:                 controller-uid=d76e37f9-bc02-4270-9a27-c669c80d0cbb
Labels:                   objectset.rio.cattle.io/hash=6fb02a1a07227c1f395e337028a47ca6942caaa2
                          plan.upgrade.cattle.io/busybox-test=7dfd8044aa7c456209bd9a936377d75caf7b42dde345cfd6535981d1
                          upgrade.cattle.io/controller=system-upgrade-controller
                          upgrade.cattle.io/node=k3s-server-1
                          upgrade.cattle.io/plan=busybox-test
                          upgrade.cattle.io/version=1.35.0-uclibc
Annotations:              batch.kubernetes.io/job-tracking:
                          objectset.rio.cattle.io/applied:
                            H4sIAAAAAAAA/+xWW2/bOBP9KwWfJUe2fIkNfA/+YndrtHGMOu2iKIJgRI5srilSS46cGIb/+4KS4sjNpWn3dWHAEC8zPDxzZoZ7liGBAAI22jPQ2hCQNNr5oUn+Qk4OqWWlaXEgUt...
                          objectset.rio.cattle.io/id: system-upgrade-controller
                          objectset.rio.cattle.io/owner-gvk: upgrade.cattle.io/v1, Kind=Plan
                          objectset.rio.cattle.io/owner-name: busybox-test
                          objectset.rio.cattle.io/owner-namespace: system-upgrade
                          upgrade.cattle.io/ttl-seconds-after-finished: 900
Parallelism:              1
Completions:              1
Completion Mode:          NonIndexed
Start Time:               Wed, 13 Jul 2022 13:17:25 -0700
Completed At:             Wed, 13 Jul 2022 13:18:29 -0700
Duration:                 64s
Active Deadline Seconds:  900s
Pods Statuses:            0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=d76e37f9-bc02-4270-9a27-c669c80d0cbb
           job-name=apply-busybox-test-on-k3s-server-1-with-7dfd8044aa7c45620-3655e
           plan.upgrade.cattle.io/busybox-test=7dfd8044aa7c456209bd9a936377d75caf7b42dde345cfd6535981d1
           upgrade.cattle.io/controller=system-upgrade-controller
           upgrade.cattle.io/node=k3s-server-1
           upgrade.cattle.io/plan=busybox-test
           upgrade.cattle.io/version=1.35.0-uclibc
  Containers:
   upgrade:
    Image:      local.registry.k3s.khaus/e6b2900c03ccaf3a32b6020cadfdfc46eac4889ddf603ea39d66082504a5e7c3/busybox:1.35.0-uclibc
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
    Args:
      -c
      sleep 60
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:              (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            busybox-test
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     7dfd8044aa7c456209bd9a936377d75caf7b42dde345cfd6535981d1
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  1.35.0-uclibc
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
  Volumes:
   host-root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  Directory
   pod-info:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  5m16s  job-controller  Created pod: apply-busybox-test-on-k3s-server-1-with-7dfd8044aa7c45620-fg55r
  Normal  Completed         4m12s  job-controller  Job completed
```
