### ISSUE TITLE
Conflict between privileged and allowPrivilegeEscalation

### ISSUE THREAD

**Issue by akelge** [rancher/system-upgrade-controller#303]
In the manifest we have
```
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
```
but in the deployment there is
```
        securityContext:
          allowPrivilegeEscalation: false
```

This is causing a failure in deploying, at least on rke2 1.28.8, I think that the solution would be to set `allowPrivilegeEscalation` to `true`
