### ISSUE TITLE
Allow same-version plan to run again

### ISSUE THREAD

**Issue by jflambert** [rancher/system-upgrade-controller#315]
**Describe the solution you'd like**
I'd like to be able to run the same plan multiple times, even if the version is exactly the same

**Additional context**
Here's what I currently do:

`kubectl apply -f plan.yaml --server-side --force-conflicts`

plan.yaml

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: my-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
    - {key: node-role.kubernetes.io/master, operator: Exists}
  serviceAccountName: system-upgrade
  version: v1.0
  upgrade:
    image: my-image
```

First time I run this, I get a new plan, and a job runs.

Second time I run it, nothing happens. If I do delete the plan, it comes back, but no job.

For various reasons, I'd like the upgrade job to execute again. How can I tell SUC to allow this pattern? I see the plan has `status.latestHash` and `status.latestVersion`, how can I reset those?
