### ISSUE TITLE
Pods using /var/lib/rancher/k3s/data/current on host will break after upgrade

### ISSUE THREAD

**Issue by mnorrsken** [rancher/system-upgrade-controller#327]
**Is your feature request related to a problem? Please describe.**
When running system-upgrade without rebooting, multus daemonset(specifically) or any processes using the k3s container symlink /var/lib/rancher/k3s/data/current will be invalid after upgrade

**Describe the solution you'd like**
Possibly document somewhere that anything using /var/lib/rancher/k3s/data/current could be invalid after upgrade if not restarted.

**Describe alternatives you've considered**
I solved it like this:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multus-restarter
  namespace: kube-system
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  resourceNames:
  - multus
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multus-restarter
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: system-upgrade
    namespace: system-upgrade
roleRef:
  kind: Role
  name: multus-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: multus-plan
  namespace: system-upgrade
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  concurrency: 1
  cordon: false
  nodeSelector:
    matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - master1
  prepare:
    args:
    - prepare
    - agent-plan #agent-plan runs after server-plan, so this will run last
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
    args: ["/opt/k3s", "kubectl", "rollout", "restart", "daemonset", "multus", "-n", "kube-system"]
```
