### ISSUE TITLE
Upgrade to PRE-RELEASE fails, because image not available

### ISSUE THREAD

**Issue by janpieper** [rancher/system-upgrade-controller#339]
**Version**

v0.14.2

**Platform/Architecture**

Linux, K3s (v1.31.2-k3s1)

**Describe the bug**

We're running a k3s cluster with a system-upgrade-controller. This night, the upgrade failed because the docker image for the new version does not exist yet. Most likely because the newly released version is only a PRE-RELEASE.

https://github.com/k3s-io/k3s/releases/tag/v1.31.3+k3s1 (2024-12-05 05:56:15 UTC)

![Screenshot from 2024-12-05 06-56-29](https://github.com/user-attachments/assets/cda7e804-3467-4892-9cb9-d261ec56167e)

Don't know whether this is a problem of the system-upgrade-controller or with the k3s-project not pushing the docker image to the registry :man_shrugging: 

**To Reproduce**

Have a PRE-RELEASE in the configured channel (e.g. `https://update.k3s.io/v1-release/channels/v1.31`)

**Expected behavior**

No upgrade is triggered.

**Actual behavior**

The upgrade pods are failing with `Init:ImagePullBackOff` and `ErrImagePull` because the docker images do not exist yet...

**Additional context**

```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  labels:
    k3s_upgrade: agent
  name: k3s-agent
  namespace: system-upgrade
spec:
  channel: https://update.k3s.io/v1-release/channels/v1.31
  concurrency: 1
  drain:
    disableEviction: false
    force: true
    skipWaitForDeleteTimeout: 60
  nodeSelector:
    matchExpressions:
    - key: k3s_upgrade
      operator: Exists
    - key: k3s_upgrade
      operator: NotIn
      values:
      - disabled
      - "false"
    - key: node-role.kubernetes.io/control-plane
      operator: NotIn
      values:
      - "true"
    - key: kured
      operator: NotIn
      values:
      - rebooting
  prepare:
    args:
    - prepare
    - k3s-server
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  tolerations:
  - effect: NoSchedule
    key: server-usage
    operator: Equal
    value: storage
  - operator: Exists
  upgrade:
    image: rancher/k3s-upgrade
```
