### ISSUE TITLE
Failed to validate plan: spec.window is invalid

### ISSUE THREAD

**Issue by laurenz-glueck** [rancher/system-upgrade-controller#342]
**Version**
v0.15.0-rc1

**Describe the bug**
I have updated the system-update-controller in my cluster to v0.15.0-rc1 by applying the `system-upgrade-controller.yaml` and `crd.yaml` of version v0.15.0-rc1.

After that I have added this in the `spec:` section of my `Plan` (as mentioned by @brandond here #335 ):

```
    window:
        days:
            - "saturday"
        startTime: "00:15"
        endTime: "06:15"
        timeZone: "Europe/Berlin"
```

But when I apply the plan I get this warning in the system-update-controller pod logs:
```
"Event occurred" object="system-upgrade/k3s-agent" fieldPath="" kind="Plan" apiVersion="upgrade.cattle.io/v1" 
type="Warning" reason="ValidateFailed" message="Failed to validate plan: spec.window is invalid"
```

**Comment by brandond** [comment]
I suspect that maybe tzdb is missing from the helm-controller image? We run it embedded in other projects where the tzdb files are available so this may have been an oversight.

Does it work if you leave the timezone unspecified or `UTC` as shown in the example?

**Comment by laurenz-glueck** [comment]
I just tried it with `timeZone: "UTC"` and without the timezone unspecified.
Unfortunately I get the same error message for both cases.

**Comment by laurenz-glueck** [comment]
This is the full `Plan` I am using:

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
    labels:
        k3s_upgrade: agent
    name: k3s-agent
    namespace: system-upgrade
spec:
    channel: https://update.k3s.io/v1-release/channels/v1.31
    concurrency: 1
    drain:
        disableEviction: false
        force: true
        skipWaitForDeleteTimeout: 60
    nodeSelector:
        matchExpressions:
            -   key: k3s_upgrade
                operator: Exists
            -   key: k3s_upgrade
                operator: NotIn
                values:
                    - disabled
                    - "false"
            -   key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                    - "true"
            -   key: kured
                operator: NotIn
                values:
                    - rebooting
    prepare:
        args:
            - prepare
            - k3s-server
        image: rancher/k3s-upgrade
    serviceAccountName: system-upgrade
    tolerations:
        -   effect: NoSchedule
            key: server-usage
            operator: Equal
            value: storage
        -   operator: Exists
    upgrade:
        image: rancher/k3s-upgrade
    window:
        days:
            - "saturday"
        startTime: "00:15"
        endTime: "06:15"
        timeZone: "Europe/Berlin"
```

Maybe that helps reproducing the issue?
Without the `window` part I don't get any error.

**Comment by brandond** [comment]
Yeah, its just the missing TZDB files. Works fine for me with:
```yaml
    window:
      days:
        - "saturday"
      startTime: "0:15"
      endTime: "6:00"
      timeZone: "UTC"
```

**Comment by laurenz-glueck** [comment]
You are right - I just tried again with `UTC` and now it works! No idea why it didn't last time when I tried...

So it is the missing TZDB files.

**Comment by brandond** [comment]
Try again with 0.15.0-rc2. The error better indicates the issue, and time zone names should now work:

```yaml
    - lastUpdateTime: "2025-01-28T03:46:41Z"
      message: spec.window is invalid, unknown time zone foo/bar
      reason: Error
      status: "False"
      type: Validated
```

```yaml
    window:
      days:
      - saturday
      endTime: "06:00"
      startTime: "0:15"
      timeZone: US/Pacific
  status:
    conditions:
    - lastUpdateTime: "2025-01-28T03:48:31Z"
      reason: PlanIsValid
      status: "True"
      type: Validated
```
