### ISSUE TITLE
Update Ubuntu on cluster nodes with system-upgrade-controller fails

### ISSUE THREAD

**Issue by steffeneichler** [rancher/system-upgrade-controller#345]
Hi,

I tried to upgrade Ubuntu based nodes in our cluster. I created a plan according the [examples](https://github.com/rancher/system-upgrade-controller/blob/master/examples/ubuntu/bionic.yaml) given in official git project.

After I applied the required resources,  system-upgrade-controller starts a pod, drains the node, but upgrade container fails because it is not able to chroot into hosts filesystem.
Failure message is:
```
chroot: cannot change root directory to '/host': Operation not permitted
```

Here my deployment code.
```
apiVersion: v1
kind: Secret
metadata:
  name: os-upgrade
  namespace: cattle-system
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    export DEBIAN_FRONTEND=noninteractive
    secrets=$(dirname $0)
    apt-get update
    apt-get upgrade -yq
    if [ -f /run/reboot-required ]; then
      cat /run/reboot-required
      #reboot
      date > /tmp/i_had_rebooted_if_i_would_be_armed
    fi
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: worker-os-upgrade-plan
  namespace: cattle-system
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/os, operator: In, values: ["linux"]}
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: os-upgrade
      path: /host/run/system-upgrade/secrets/os-upgrade
  cordon: true
  drain:
    force: true
    deleteLocalData: true
    ignoreDaemonSets: true
  version: jammy
  upgrade:
    image: mtr.devops.telekom.de/base/ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/os-upgrade/upgrade.sh"]
```

If the upgrade pod would be started with proper sec context
```
  securityContext:
    runAsUser: 0
    runAsGroup: 0
```
it would be able to run the update. I tested this with a pod with same definitions as created from system-upgrade-controller.

How  can I configure a plan resource  which results in a correct configured pod?

regards
Steffen
