### ISSUE TITLE
SUC pod failing due to `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by pavansokkenagaraj** [rancher/system-upgrade-controller#349]
**Version** 
0.11.0

**Platform/Architecture** 
SLES Micro

**Describe the bug**

SUC pod container crashing with `fatal error: concurrent map writes` and the succeeding container which comes up is failing to list Jobs with Unauthorized error 

**To Reproduce**

Issue is intermittent and not reproducible

**Expected behavior**

Even if the pod fails due to concurrent map writes, the next container should run

**Actual behavior**

succeeding container having Unauthorized error

**Additional context**

SUC pod fails due to `concurrent map writes` with the below err:
<details>
  <summary>fatal error: concurrent map writes</summary>
  <p><code>time="2025-02-10T01:57:14Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade-67a1aa325663728b78826cf4/ntp-update@3368654, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2025-02-10T01:57:14Z LastTransitionTime: Reason:Version Message:}] LatestVersion:14089859268069756436 LatestHash:3cc2e4e1a471af79422d2d1f876dc3425e674827bf3b9c1b351695c6 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func1" file="/workspace/pkg/upgrade/handle_upgrade.go:30"
time="2025-02-10T01:57:14Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade-67a1aa325663728b78826cf4/ntp-update@3368654, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2025-02-10T01:57:14Z LastTransitionTime: Reason:Version Message:}] LatestVersion:14089859268069756436 LatestHash:3cc2e4e1a471af79422d2d1f876dc3425e674827bf3b9c1b351695c6 Applying:[]}" func="github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handlePlans.func2" file="/workspace/pkg/upgrade/handle_upgrade.go:68"
fatal error: concurrent map writes

goroutine 204 [running]:
github.com/rancher/system-upgrade-controller/pkg/upgrade.(*Controller).handleJobs.func1({0x4d5d28?, 0xc000c55c08?}, 0xc0012da508)
	/workspace/pkg/upgrade/handle_batch.go:88 +0x71d
github.com/rancher/wrangler/pkg/generic.(*Controller[...].func1({0x1af0428?, 0xc0012da508?})
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230425173236-39a4707f0689/pkg/generic/controller.go:162 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x40957b?, {0xc0009d2620?, 0x415c6f?}, {0x1af0428?, 0xc0012da508?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000796910, {0xc0009d2620, 0x67}, {0x1af0428, 0xc0012da508})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:75 +0x202
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000164c60, {0xc0009d2620, 0x67})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:233 +0x12e
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000164c60, {0x1635c80, 0xc0010745a0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:214 +0xeb
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000164c60)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:191 +0x45
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.7-rc.0/pkg/util/wait/wait.go:155 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0010de240, {0x1aecbc0, 0xc000f84270}, 0x1, 0xc00059a0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.7-rc.0/pkg/util/wait/wait.go:156 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0010de240, 0x3b9aca00, 0x0, 0x1, 0xc00059a0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.7-rc.0/pkg/util/wait/wait.go:133 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.7-rc.0/pkg/util/wait/wait.go:90
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 696
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x314

goroutine 1 [chan receive, 248 minutes]:
main.Run(0xc0004a0b00?)
	/workspace/main.go:104 +0x186
github.com/urfave/cli.HandleAction({0x163b0c0?, 0x19991c8?}, 0xc0005836c0?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:525 +0x75
github.com/urfave/cli.(*App).Run(0xc0005836c0, {0xc000040170, 0x1, 0x1})
	/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:285 +0x7e6
main.main()
	/workspace/main.go:82 +0x6ad

goroutine 130 [syscall, 248 minutes]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	/usr/local/go/src/os/signal/signal.go:151 +0x1f

goroutine 131 [chan receive, 248 minutes]:
github.com/rancher/wrangler/pkg/signals.SetupSignalContext.func1()
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230425173236-39a4707f0689/pkg/signals/signal.go:45 +0x25
created by github.com/rancher/wrangler/pkg/signals.SetupSignalContext in goroutine 1
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230425173236-39a4707f0689/pkg/signals/signal.go:44 +0xda

goroutine 106 [chan receive, 248 minutes]:
github.com/rancher/lasso/pkg/controller.(*SharedHandler).Register.func1()
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:49 +0x4a
created by github.com/rancher/lasso/pkg/controller.(*SharedHandler).Register in goroutine 1
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:48 +0x24c

goroutine 137 [IO wait]:
internal/poll.runtime_pollWait(0x7f28b87f9700, 0x72)
	/usr/local/go/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000498100?, 0xc0006ce000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000498100, {0xc0006ce000, 0xc000, 0xc000})
	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000498100, {0xc0006ce000?, 0x7f28b7ffc040?, 0xc001132018?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0001ba040, {0xc0006ce000?, 0xc000655918?, 0x413bdb?})
	/usr/local/go/src/net/net.go:185 +0x45
crypto/tls.(*atLeastReader).Read(0xc001132018, {0xc0006ce000?, 0x0?, 0xc001132018?})
	/usr/local/go/src/crypto/tls/conn.go:806 +0x3b
bytes.(*Buffer).ReadFrom(0xc0000049b0, {0x1aed2a0, 0xc001132018})
	/usr/local/go/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000004708, {0x1aecd20, 0xc0001ba040}, 0xc000655960?)
	/usr/local/go/src/crypto/tls/conn.go:828 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000004708, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:626 +0x3cf
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:588
crypto/tls.(*Conn).Read(0xc000004708, {0xc0002d6000, 0x1000, 0x877009?})
	/usr/local/go/src/crypto/tls/conn.go:1370 +0x156
bufio.(*Reader).Read(0xc000792060, {0xc00021c2e0, 0x9, 0x0?})
	/usr/local/go/src/bufio/bufio.go:241 +0x197
io.ReadAtLeast({0x1aec320, 0xc000792060}, {0xc00021c2e0, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:335 +0x90
io.ReadFull(...)
	/usr/local/go/src/io/io.go:354
golang.org/x/net/http2.readFrameHeader({0xc00021c2e0, 0x9, 0x164e0c0?}, {0x1aec320?, 0xc000792060?})
	/go/pkg/mod/golang.org/x/net@v0.17.0/http2/frame.go:237 +0x65
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00021c2a0)
	/go/pkg/mod/golang.org/x/net@v0.17.0/http2/frame.go:498 +0x85
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000655fa8)
	/go/pkg/mod/golang.org/x/net@v0.17.0/http2/transport.go:2275 +0x12c
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0002d4000)
	/go/pkg/mod/golang.org/x/net@v0.17.0/http2/transport.go:2170 +0x65
created by golang.org/x/net/http2.(*Transport).newClientConn in goroutine 136
	/go/pkg/mod/golang.org/x/net@v0.17.0/http2/transport.go:821 +0xca6</code></p>
</details>

Container status
```yaml
    containerStatuses:
    - containerID: containerd://b7eb11f0937100bae661b0a292f8fa3a58b9e7b098427feb75f8a63457a2a96e
      image: system-upgrade-controller:v0.11.6
      imageID: sha256:95543ab6e812fd0f9c4a0dc68d5c86bfba45836d8bd4705a3ef62f459757ef9a
      lastState:
        terminated:
          containerID: containerd://56a1731404cf61710c5f9fd086445f70e775ca295218360f98ea736047f685ec
          exitCode: 2
          finishedAt: "2025-02-10T01:58:54Z"
          reason: Error
          startedAt: "2025-02-09T21:50:05Z"
      name: system-upgrade-controller
      ready: true
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2025-02-10T01:58:54Z"
      volumeMounts:
      - mountPath: /etc/ssl
        name: etc-ssl
      - mountPath: /etc/pki
        name: etc-pki
      - mountPath: /etc/ca-certificates
        name: etc-ca-certificates
      - mountPath: /tmp
        name: tmp
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-w44pm
        readOnly: true
        recursiveReadOnly: Disabled
```

and the subsequent container which comes up has Unauthorized err to run any kube api calls
```
time="2025-02-12T11:12:26Z" level=error msg="error syncing 'system-upgrade-67a1aa325663728b78826cf4/public-key-manager-plan': handler system-upgrade-controller: Unauthorized, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller system-upgrade-67a1aa325663728b78826cf4/public-key-manager-plan: Unauthorized, requeuing" func="github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem" file="/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:193"
time="2025-02-12T11:12:26Z" level=error msg="error syncing 'system-upgrade-67a1aa325663728b78826cf4/ntp-update': handler system-upgrade-controller: Unauthorized, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller system-upgrade-67a1aa325663728b78826cf4/ntp-update: Unauthorized, requeuing" func="github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem" file="/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:193"
```

** I have verified that the SA/cluster-role/role-bindings exist and only thing I can think of is that service-account token could be expired
