### ISSUE TITLE
Another case of "x509: certificate signed by unknown authority, requeuing"

### ISSUE THREAD

**Issue by bmbeverst** [rancher/system-upgrade-controller#358]
**Version**

system-upgrade-controller version v0.15.2 (b1a9781)

**Platform/Architecture**

linux-amd64  Flatcar Container Linux stable 4152.2.2 for QEMU (immutable)

**Describe the bug**

```
```

system-upgrade-controller is not able to upgade 
I can connect with curl, but I only have one symlink file. There is no `/etc/pki` or `/etc/tls`. Any assistance would be appreciated! 

I have one syslinked file:
```
$ ls -l /etc/ssl/
drwxr-xr-x. 1 root root 14388 Feb 13 18:28 certs
-rw-r--r--. 1 root root   241 Feb 13 18:26 fipsmodule.cnf
lrwxrwxrwx. 1 root root    31 Feb 13 16:59 openssl.cnf -> ../../usr/share/ssl/openssl.cnf
drwx------. 1 root root     0 Feb 13 18:36 private

```

I tried adding a file mount

```
          name: tmp
        - mountPath: /usr/share/ssl/openssl.cnf
          name: usr-ssl
          readOnly: true
 . . . 
      - hostPath:
          path: /etc/ssl/openssl.cnf
          type: File
        name: usr-ssl


```

### curl
```
curl https://update.k3s.io/v1-release/channels/stable
<a href="https://github.com/k3s-io/k3s/releases/tag/v1.31.6+k3s1">Found</a>.
```

**To Reproduce**

Use the following in your plan instead of a `version`:

`channel: https://update.k3s.io/v1-release/channels/stable`

**Expected behavior**

Expect that the SSL certificate can be verified from the container.

**Actual behavior**

The SSL configuration is missing files from the host.

**Additional context**

The bug was reported multiple times in different constellations:

- #94
- #105
- #243
- #278 

I am unable to access the container to see what files are actually in the `/etc/ssl/` folder.
