### ISSUE TITLE
K3s Server Upgrade Job Fails to Schedule Due to Self-Blocking PodAntiAffinity

### ISSUE THREAD

**Issue by krohrsb** [rancher/system-upgrade-controller#359]
**Version**

v0.15.2

**Platform/Architecture**

Kubernetes - linux-amd64

**Describe the bug**

I am encountering an issue where the system-upgrade-controller creates a Job to upgrade K3s server nodes, but this Job consistently fails to schedule due to a podAntiAffinity rule that seems to block the pod itself. At least, that is how I'm interpreting it. I'm not sure what else would be the issue? Apologies otherwise.

**To Reproduce**

1. Apply a Plan to upgrade the K3s server node(s). (I can provide mine if necessary) 
1. Observe that the system-upgrade-controller creates a Job (e.g., `apply-k3s-server-on-<node>-with-<hash>`).
1. This Job's pod remains in a Pending state.
1. Describing the pod (`kubectl describe pod -n system-upgrade <pod-name>`) shows the following in the "Reason" and "Message" fields:

FailedScheduling | 0/4 nodes are available: 1 node(s) didn't satisfy existing pods anti-affinity rules, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 1 No preemption victims found for incoming pod, 3 Preemption is not helpful for scheduling.

1. Examining the pod's specification (using `kubectl get job -n system-upgrade <job-name> -o yaml`) reveals a podAntiAffinity rule similar to:

```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: upgrade.cattle.io/plan
          operator: In
          values:
          - k3s-server
      topologyKey: kubernetes.io/hostname
```

The pod being scheduled itself has the label upgrade.cattle.io/plan=k3s-server, leading to the anti-affinity rule preventing it from being scheduled on any node (including the target node, even if no other pods with this label exist yet). At least that is my presumption.

1. Similarly, executing `kubectl get pods -A -l upgrade.cattle.io/plan=k3s-server -o wide` shows *only* the pending `apply-k3s-server-on-<node>-with-<hash>` pod.

**Expected behavior**

The upgrade Job pod should be able to schedule on the designated control plane node to perform the upgrade, even though it will have the upgrade.cattle.io/plan=k3s-server label. The anti-affinity rule should ideally prevent subsequent upgrade pods for the same plan from running on the same node concurrently, but not block the initial pod.

**Actual behavior**

The upgrade Job pod remains in a Pending state indefinitely due to the self-referential podAntiAffinity rule. The system-upgrade-controller continues to enqueue the Job.

**Additional context**

K3s version: v1.32.1+k3s1 (attempting to upgrade to v1.32.3+k3s1)
Single control plane node setup (with 3 other workers)
Upgrade Plan configured for k3s-server with concurrency: 1.

**Comment by brandond** [comment]
What does the actual plan look like?

**Comment by krohrsb** [comment]
So I was digging further, and this may be due to the other anti affinity:

```
 podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - system-upgrade-controller
          topologyKey: kubernetes.io/hostname
```

Which makes more sense. Kustomize was spreading the app.kubernetes.io/name label across all resources defeating the purpose here. So this was my mistake, and i found it just a tad too late to avoid wasting your time. Apologies
