### ISSUE TITLE
Incorrect apiVersion in System Upgrade Controller

### ISSUE THREAD

**Issue by przemytn** [rancher/system-upgrade-controller#360]
# Version
v0.15.2
# Platform/Architecture
linux-amd64
# Describe the bug
The **Chart.yam**l file uses incorrect apiVersion. Currently using **apiVersion: v1** when it should be **apiVersion: v2**. This causes annotations to not be utilized properly as the v1 version doesn't fully support the annotations structure. Also note that issues are currently disabled on RKE2 charts repository. Currently apiVersion v1 in [charts](https://github.com/rancher/charts/tree/dev-v2.11/charts/system-upgrade-controller) exist in every version.

# To Reproduce

Check the **Chart.yaml** file in the rke2 system-upgrade-controller repository
Notice that the apiVersion is set to v1 instead of v2
Try to use the annotations provided in the Chart

# Expected behavior
The Chart.yaml should use apiVersion: v2 to properly support the annotations feature set. This would allow the catalog annotations to function correctly.
# Actual behavior
**Current Chart.yaml contains:**
``` yaml
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.25.0-0 < 1.33.0-0'
  catalog.cattle.io/managed: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.11.0-0'
  catalog.cattle.io/release-name: system-upgrade-controller
apiVersion: v1
appVersion: v0.15.2
description: General purpose controller to make system level updates to nodes.
home: https://github.com/rancher/system-upgrade-controller
kubeVersion: '>= 1.25.0-0'
name: system-upgrade-controller
version: 106.0.0
```
But should be:
```yaml
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.25.0-0 < 1.33.0-0'
  catalog.cattle.io/managed: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.11.0-0'
  catalog.cattle.io/release-name: system-upgrade-controller
apiVersion: v2
appVersion: v0.15.2
description: General purpose controller to make system level updates to nodes.
home: https://github.com/rancher/system-upgrade-controller
kubeVersion: '>= 1.25.0-0'
name: system-upgrade-controller
version: 106.0.0
```
# Additional context
The change from apiVersion v1 to v2 is needed for proper Helm chart functionality. The annotations section is not fully supported in Helm chart apiVersion v1. Note that issues on RKE2 charts are currently disabled, so this bug report i had to make here.
