### ISSUE TITLE
Tolerations are ignored

### ISSUE THREAD

**Issue by jcambronero** [rancher/system-upgrade-controller#76]
**Version**
rancher/system-upgrade-controller:v0.4.0

**Describe the bug**
The plan tolerations are ignored. The jobs created from the plan do not have the tolerations specified in the plan definition.

**To Reproduce**
Create a new plan and add the following tolerations:
```
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    operator: Exists
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Exists
```

Deploy the plan and attempt to patch a Kubernetes control plane + etcd node (which should have the following taints):
```
Taints:             node-role.kubernetes.io/etcd=true:NoExecute
                    node-role.kubernetes.io/controlplane=true:NoSchedule
```
The tolerations section in the job that is created from the plan looks like this (all the tolerations defined in the plan are ignored):
```
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
```

Therefore the pod created from the job remains in pending state forever, with the following error:
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  16s (x2 over 16s)  default-scheduler  0/12 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 11 node(s) didn't match node selector.
```

**Expected behavior**
The tolerations should be set as defined in the plan so that the job can be executed.

**Actual behavior**
The pod remains in pending state forever.

**Comment by billimek** [comment]
I think this feature was introduced in v0.5.0

**Comment by dweomer** [comment]
> I think this feature was introduced in v0.5.0

Yep, as mentioned in the [v0.5.0 release notes](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.5.0).

There are no plans to back-port this to v0.4.x at this time. Please upgrade your SUC deployment to use the v0.5.0 image.

**Comment by soakes** [comment]
While this is closed, it comes up as a top result on google with the same issue that I suffered.  To save people scratching their head for the solution.  I am pasting it below alongside my config of cluster before its rebuild to final/prod version.

So the problem is that you should make sure your using the `latest` version of the `system-upgrade-controller.yaml` which is availble [here](https://rancher.com/docs/k3s/latest/en/upgrades/automated/): 

You also need to add the tolerations if you build your cluster so that your masters wont run anything non-critical.

I build my inital master as follows:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION='v1.21.10+k3s1' INSTALL_K3S_EXEC="server --cluster-init --node-name kube-m01 --node-ip 10.27.192.101 --cluster-cidr=10.254.0.0/18 --service-cidr=10.254.64.0/18 --tls-san api-kube-proxy.prod.example.io --tls-san api-kube-proxy --flannel-iface=eth0 --disable servicelb --disable local-storage --disable metrics-server --disable-cloud-controller --node-taint CriticalAddonsOnly=true:NoExecute" sh -
```

Extra masters (two extra) gets added with a slighly moddifed version of above with respective hostname and IP's changed:
```
export TOKEN=K1084cb55dfcbfe8f01849d86f838a4c64a48cb68e1f0964724c5671d56ca5e35b7::server:20e57a4b6f20dc66f668bc50d72e2778

curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION='v1.21.10+k3s1' K3S_TOKEN=$TOKEN INSTALL_K3S_EXEC="server --server https://api-kube-proxy.prod.example.io:6443 --node-name kube-m02 --node-ip 10.27.192.102 --cluster-cidr=10.254.0.0/18 --service-cidr=10.254.64.0/18 --flannel-iface=eth0 --disable servicelb --disable local-storage --disable metrics-server --disable-cloud-controller --node-taint CriticalAddonsOnly=true:NoExecute" sh -
unset TOKEN
```

Workers added as follows with replaced hostname and IP where required:

```
export TOKEN=K1084cb55dfcbfe8f01849d86f838a4c64a48cb68e1f0964724c5671d56ca5e35b7::server:20e57a4b6f20dc66f668bc50d72e2778

curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION='v1.21.10+k3s1' K3S_TOKEN=$TOKEN K3S_URL=https://api-kube-proxy.prod.example.io:6443 INSTALL_K3S_EXEC="--node-name kube-n01 --node-ip 10.27.192.104" sh -
unset TOKEN
```

Below is a snipet of what I am using for the **upgrade-config**, which will pool for latest release and update one node at a time when required for zero downtime solution.

**upgrade-config.yaml**
```
# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    operator: Exists
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Exists
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```

and thats all you need.  

Hopefully someone who finds this via google finds it useful.

---

**Before**
```
❯ k get all -A
NAMESPACE        NAME                                                                  READY   STATUS      RESTARTS   AGE
kube-system      pod/coredns-6c46d74d64-tbsrg                                          1/1     Running     0          10m
kube-system      pod/helm-install-traefik-crd-xwtkd                                    0/1     Completed   0          10m
kube-system      pod/helm-install-traefik-pcwws                                        0/1     Completed   1          10m
kube-system      pod/traefik-56c4b88c4b-kqfpx                                          1/1     Running     0          4m18s
system-upgrade   pod/apply-agent-plan-on-kube-n03-with-485ff2dde3cb6331df7d0cd-drvtn   0/1     Init:0/2    0          15s
system-upgrade   pod/apply-server-plan-on-kube-m02-with-485ff2dde3cb6331df7d0c-f7676   0/1     Pending     0          16s
system-upgrade   pod/system-upgrade-controller-c48cb89f9-7z28k                         1/1     Running     0          65s

NAMESPACE     NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       service/kubernetes   ClusterIP      10.254.64.1     <none>        443/TCP                      10m
kube-system   service/kube-dns     ClusterIP      10.254.64.10    <none>        53/UDP,53/TCP,9153/TCP       10m
kube-system   service/traefik      LoadBalancer   10.254.90.125   <pending>     80:31630/TCP,443:32329/TCP   4m19s

NAMESPACE        NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system      deployment.apps/coredns                     1/1     1            1           10m
kube-system      deployment.apps/traefik                     1/1     1            1           4m19s
system-upgrade   deployment.apps/system-upgrade-controller   1/1     1            1           65s

NAMESPACE        NAME                                                  DESIRED   CURRENT   READY   AGE
kube-system      replicaset.apps/coredns-6c46d74d64                    1         1         1       10m
kube-system      replicaset.apps/traefik-56c4b88c4b                    1         1         1       4m19s
system-upgrade   replicaset.apps/system-upgrade-controller-c48cb89f9   1         1         1       65s

NAMESPACE        NAME                                                                        COMPLETIONS   DURATION   AGE
kube-system      job.batch/helm-install-traefik                                              1/1           5m48s      10m
kube-system      job.batch/helm-install-traefik-crd                                          1/1           5m46s      10m
system-upgrade   job.batch/apply-agent-plan-on-kube-n03-with-485ff2dde3cb6331df7d0cd-7f199   0/1           15s        15s
system-upgrade   job.batch/apply-server-plan-on-kube-m02-with-485ff2dde3cb6331df7d0c-edbbf   0/1           16s        16s
```

```
❯ k get nodes
NAME       STATUS                     ROLES                       AGE   VERSION
kube-m01   Ready                     control-plane,etcd,master   22m   v1.21.10+k3s1
kube-m02   Ready                     control-plane,etcd,master   17m   v1.21.10+k3s1
kube-m03   Ready                     control-plane,etcd,master   17m   v1.21.10+k3s1
kube-n01   Ready                      <none>                      16m   v1.21.10+k3s1
kube-n02   Ready                      <none>                      16m   v1.21.10+k3s1
kube-n03   Ready                      <none>                      16m   v1.21.10+k3s1
```


**After**
```
❯ k get all -A
NAMESPACE        NAME                                            READY   STATUS      RESTARTS   AGE
kube-system      pod/coredns-96cc4f57d-2c2k2                     1/1     Running     0          19m
kube-system      pod/helm-install-traefik--1-7vwfz               0/1     Completed   0          18m
kube-system      pod/helm-install-traefik-crd--1-f8xfk           0/1     Completed   0          18m
kube-system      pod/traefik-56c4b88c4b-kqfpx                    1/1     Running     0          35m
system-upgrade   pod/system-upgrade-controller-8677c8fb4-bms6j   1/1     Running     0          23m

NAMESPACE     NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       service/kubernetes   ClusterIP      10.254.64.1     <none>        443/TCP                      41m
kube-system   service/kube-dns     ClusterIP      10.254.64.10    <none>        53/UDP,53/TCP,9153/TCP       41m
kube-system   service/traefik      LoadBalancer   10.254.90.125   <pending>     80:31630/TCP,443:32329/TCP   35m

NAMESPACE        NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system      deployment.apps/coredns                     1/1     1            1           41m
kube-system      deployment.apps/traefik                     1/1     1            1           35m
system-upgrade   deployment.apps/system-upgrade-controller   1/1     1            1           23m

NAMESPACE        NAME                                                  DESIRED   CURRENT   READY   AGE
kube-system      replicaset.apps/coredns-6c46d74d64                    0         0         0       41m
kube-system      replicaset.apps/coredns-96cc4f57d                     1         1         1       19m
kube-system      replicaset.apps/traefik-56c4b88c4b                    1         1         1       35m
system-upgrade   replicaset.apps/system-upgrade-controller-8677c8fb4   1         1         1       23m

NAMESPACE     NAME                                 COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik       1/1           9s         18m
kube-system   job.batch/helm-install-traefik-crd   1/1           3s         18m
```

```
❯ k get nodes
NAME       STATUS   ROLES                       AGE   VERSION
kube-m01   Ready    control-plane,etcd,master   44m   v1.22.7+k3s1
kube-m02   Ready    control-plane,etcd,master   39m   v1.22.7+k3s1
kube-m03   Ready    control-plane,etcd,master   38m   v1.22.7+k3s1
kube-n01   Ready    <none>                      38m   v1.22.7+k3s1
kube-n02   Ready    <none>                      38m   v1.22.7+k3s1
kube-n03   Ready    <none>                      38m   v1.22.7+k3s1
```
